/* ============================================================
   main.js — page assembler (AI skills × roles heat map)
   Architecture: validated pipeline outputs (processed/*.csv)
     → derived data layer (js/data/dashboard-data.js, generated by
       scripts/build_data.py — the only data source)
     → presentation (heatmap.js + template components + tokens.css)
   Single research question, single chart, methodology alongside.
   ============================================================ */

import { dashboardData as data } from "./data/dashboard-data.js";
import { attachEvidence } from "./components/evidence.js";
import { mountHeatmap, buildTips } from "./components/heatmap.js";
import { renderAboutMe } from "./components/about.js";
import { authorProfile } from "./data/author-profile.js";
import { esc } from "./lib/util.js";

const P = data.meta.population;
const fmtN = (x) => new Intl.NumberFormat("en-US").format(x);

/* ---------- page furniture ---------- */

function hero() {
  return `<header class="hero">
  <div class="container">
    <p class="hero-kicker num">AI-related jobs · ${fmtN(P.eligible)} eligible listings · ${esc(P.window_from)} → ${esc(P.window_to)}</p>
    <h1>Which AI skills do employers request for each type of role?</h1>
    <p class="hero-sub">A 3D heat map of explicitly required-or-preferred AI skills across role families — with matching job listings, evidence excerpts, and source links one click away.</p>
    <p class="hero-desc">Rows are role families; columns are standardized AI skills and capabilities (first tab) or named tools (second tab). Column height and color show the percentage of analyzable listings in that role that explicitly require or prefer the skill, on one shared 0–100% scale. Patterns in collected, remote-heavy job listings; not an estimate of the entire job market.</p>
    <div class="hero-badges">
      <span class="num">${fmtN(P.eligible)} listings</span>
      <span class="num">14 role families</span>
      <span class="num">${fmtN(P.positions)} normalized positions</span>
      <span class="num">24 skills &amp; tools</span>
      <span class="num">5 job boards</span>
    </div>
  </div>
</header>`;
}

function nav() {
  return `<nav class="topnav" aria-label="Dashboard sections">
  <ul>
    <li><a href="#heat-map">Heat map</a></li>
    <li><a href="#method">Method &amp; data</a></li>
    <li><a href="#limitations">Limitations</a></li>
    <li><a href="#about">About</a></li>
  </ul>
</nav>`;
}

/* ---------- section 02: method ---------- */

function methodSection() {
  const steps = [
    {
      label: "Population",
      h: "1,095 eligible listings",
      p: `The validated pipeline processed 1,101 candidate postings (1,035 collected 2026-09-25 + 66 restored after duplicate-quality review) and re-applied the researcher's documented AI-relevance rule, excluding 6. Posting window ${esc(P.window_from)} → ${esc(P.window_to)}; sources: Jobicy, HN “Who is hiring?” (Aug + Sep 2026), Arbeitnow, RemoteOK, Remotive.`,
    },
    {
      label: "Measure",
      h: "Required or preferred (default)",
      p: `A skill is counted once per listing when the posting explicitly requires or prefers it (status assigned by the pipeline from section headers and sentence cues; benefits and about-company text excluded). “Any mention” — including responsibilities and passing mentions — is offered as a clearly labeled secondary view.`,
    },
    {
      label: "Denominators",
      h: "Listings with scannable text per role",
      p: `Percentages use each role's analyzable listings (full or partial descriptions): 1,094 full + 1 partial overall. Rows are the 14 validated role families; the drill-down uses normalized positions with matching position-level denominators.`,
    },
    {
      label: "Skill selection",
      h: "Top 12 capabilities + top 12 tools",
      p: `Skills and tools are the standardized keywords with the highest required-or-preferred volume across the approved population (ties broken by mention volume, then name), from the pipeline's ~200-term standardized dictionary. Ordering is identical across every role and view.`,
    },
    {
      label: "Scale",
      h: "One shared 0–100% scale",
      p: `Height and color encode the same percentage everywhere — 3D and 2D views, all roles, all filters. Every listing was scanned for every keyword, so an empty cell is an observed zero, never missing data. Groups with fewer than 10 analyzable listings are flagged.`,
    },
    {
      label: "Evidence",
      h: "Every cell traces back",
      p: `Selecting a cell lists the matching postings with verbatim requirement wording, the surrounding sentence, and a link to the source listing. Selecting a role family drills down into its normalized positions using position-level denominators.`,
    },
  ];
  return `<section class="section" id="method">
  <div class="section-head"><span class="section-num num">02</span><h2>Method &amp; data</h2></div>
  <p class="section-lede">How the heat map is computed, and what each number means. The full pipeline (validation, classification, keyword extraction) is deterministic and rerunnable: <span class="num">python scripts/run_pipeline.py</span>; the visualization data layer is <span class="num">visualization/scripts/build_data.py</span>.</p>
  <div class="cellgrid cols-lg3">
    ${steps.map((s, i) => `<div class="method-step">
      <span class="step-label num">STEP ${String(i + 1).padStart(2, "0")} · ${esc(s.label)}</span>
      <h3>${esc(s.h)}</h3><p>${s.p}</p>
    </div>`).join("\n")}
  </div>
</section>`;
}

/* ---------- section 03: limitations ---------- */

function limitationsSection() {
  const items = [
    { id: "COVERAGE", t: "Remote-heavy convenience sample — five accessible boards (Jobicy, HN, Arbeitnow, RemoteOK, Remotive). LinkedIn, Indeed, and Glassdoor are absent, so results cannot estimate any national or regional job market (Netherlands/EU-based demand in particular)." },
    { id: "WINDOW", t: "Single snapshot, 2026-08-03 → 2026-09-25. Nothing here supports market-growth claims, trend statements, or career rankings over time." },
    { id: "RULE-BASED", t: "Keyword extraction, required/preferred status, and role normalization are deterministic rules over employer wording — not human-audited. Original wording and excerpts are always attached; ambiguous matches are flagged in processed/requirements_extracted.csv." },
    { id: "REVIEW FLAGS", t: "157 unique listings carry open review flags (kept in analysis; see processed/review_log.csv). findings.md documents the sensitivity: excluding them shifts the top-5 role-family ranking order. Treat affected ranks as provisional." },
    { id: "SMALL GROUPS", t: "Families with fewer than 10 analyzable listings (Content / Writing n=8, Research n=3) and small positions are flagged; their percentages are illustrative only." },
    { id: "COUNTING", t: "Each skill is counted once per listing even when both required and preferred (overlaps are shown). Required vs preferred split reflects employer wording, not verified weight. An unmentioned skill is never an unnecessary skill." },
  ];
  return `<section class="section" id="limitations">
  <div class="section-head"><span class="section-num num">03</span><h2>Limitations</h2></div>
  <p class="section-lede">Stated plainly, next to the chart — the same caveats the validated handoff carries.</p>
  <div class="cellgrid cols-lg2">
    ${items.map((i) => `<div class="limitation"><span class="lim-id num">${esc(i.id)}</span>${esc(i.t)}</div>`).join("\n")}
  </div>
</section>`;
}

function footer() {
  return `<footer class="footer">
  <div class="container">
    <p class="footer-kicker num">Provenance chain</p>
    <p>raw/ — five job boards fetched 2026-09-25 (preserved as fetched) → processed/dataset.csv — 1,035 unique AI-relevant postings → validated pipeline (scripts/run_pipeline.py) — relevance re-validation, duplicate-quality review (66 restored), classification, requirement extraction → processed/role_ai_skills.csv · role_summary.csv · jobs_classified.csv · requirements_extracted.csv → visualization/scripts/build_data.py — deterministic derived data layer → this dashboard.</p>
    <p>Analysis population: ${fmtN(P.eligible)} eligible listings (${fmtN(P.full_desc)} full + ${fmtN(P.partial_desc)} partial descriptions), ${esc(P.window_from)} → ${esc(P.window_to)}. Percentages are shares of each role's analyzable listings in this dataset — not of the job market. Do not deploy without re-reading the limitations.</p>
  </div>
</footer>`;
}

/* ---------- assemble ---------- */

const app = document.getElementById("app");

app.innerHTML = `
${hero()}
${nav()}
<main class="container">
  <section class="section" id="heat-map">
    <div class="section-head"><span class="section-num num">01</span><h2>Role × AI-skill heat map</h2></div>
    <p class="section-lede">Hover, focus, or tap any column for the exact percentage, counts, and warnings; select a cell for supporting listings and source links; select a role family to drill into its normalized positions.</p>
    <div id="heatmap-app"></div>
  </section>
  ${methodSection()}
  ${limitationsSection()}
</main>
${renderAboutMe(authorProfile)}
${footer()}`;

/* mount chart + evidence system */
const hmRoot = document.getElementById("heatmap-app");
mountHeatmap(hmRoot, data);
attachEvidence(app, { tips: buildTips(data) });
